---
- name: config | Creating Observium DB
  mysql_db:
    name: "{{ observium_db_info.db }}"
    state: "present"

- name: config | Creating Observium DB Permissions
  mysql_user:
    name: "{{ observium_db_info.user }}"
    password: "{{ observium_db_info.password }}"
    priv: "observium.*:ALL"

- name: config | Configuring Observium
  template:
    src: "config.php.j2"
    dest: "{{ observium_base_dir }}/config.php"

- name: config | Creating Logs and Graph Directories
  file:
    path: "{{ item }}"
    state: "directory"
  with_items:
    - '{{ observium_base_dir }}/logs'
    - '{{ observium_base_dir }}/rrd'

- name: config | Setting Permissions on Graph Directory
  file:
    path: "{{ observium_base_dir }}/rrd"
    state: "directory"
    owner: "{{ web_owner }}"
    group: "{{ web_group }}"
    recurse: yes

- name: config | Checking if Observium DB Has Been Populated
  stat:
    path: "/root/.observium_db_populated"
  register: "observium_db_populated_check"

- name: config | Populating Observium DB
  command: "{{ observium_base_dir }}/discovery.php -u"
  register: "observium_db_populated"
  when: not observium_db_populated_check.stat.exists

- name: config | Marking Observium DB as Populated
  file:
    path: "/root/.observium_db_populated"
    state: "touch"
  when: observium_db_populated.changed

