- name: Check if Certbot is installed
  stat:
    path: "/usr/bin/certbot"
  register: "check_certbot_installed"

- name: Install Certbot
  community.general.snap:
    name: certbot
    classic: true
  when: not check_certbot_installed.stat.exists

- name: Create a symbolic link
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
  when: not check_certbot_installed.stat.exists

- name: Create LetEncryptSSL
  command: certbot --nginx -d {{ item }} --non-interactive --agree-tos --email {{ dev_main_email }}
  args:
    creates: /etc/letsencrypt/live/{{ item }}/fullchain.pem
  with_items:
    - "{{ certbot_domains }}"
  ignore_errors: True

- name: Install nginx
  ansible.builtin.include_role:
    name: geerlingguy.nginx

- name: Install php
  ansible.builtin.include_role:
    name: geerlingguy.php